# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlID', models.BigIntegerField(default=0)),
                ('loc', models.CharField(max_length=50)),
                ('tel', models.CharField(default='', max_length=20)),
                ('pic', models.URLField(default='')),
                ('shopname', models.CharField(max_length=50)),
                ('service', models.FloatField(default=0)),
                ('taste', models.FloatField(default=0)),
                ('foodtype', models.CharField(max_length=50)),
                ('shoplevel', models.CharField(max_length=50)),
                ('envi', models.FloatField(default=0)),
                ('avgcost', models.IntegerField(default=0.0)),
                ('street_address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set([('urlID',)]),
        ),
        migrations.AddField(
            model_name='comment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop'),
        ),
    ]
