# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopurl', models.CharField(max_length=100)),
                ('loc', models.CharField(max_length=20)),
                ('shopname', models.CharField(max_length=50)),
                ('service', models.FloatField(default=0)),
                ('taste', models.FloatField(default=0)),
                ('commentnum', models.IntegerField(default=0)),
                ('foodtype', models.CharField(max_length=20)),
                ('shoplevel', models.CharField(max_length=20)),
                ('envi', models.FloatField(default=0)),
                ('avgcost', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop'),
        ),
    ]
