# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, default='无名', max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(default='男', max_length=1, verbose_name='性别')),
                ('latitude', models.FloatField(default=40.0, verbose_name='纬度')),
                ('longitude', models.FloatField(default=116.33, verbose_name='经度')),
                ('friend', models.ManyToManyField(related_name='_user_friend_+', to=settings.AUTH_USER_MODEL, verbose_name='friend')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlID', models.BigIntegerField(default=0)),
                ('loc', models.CharField(max_length=50)),
                ('tel', models.CharField(default='', max_length=20)),
                ('pic', models.URLField(default='')),
                ('shopname', models.CharField(max_length=50)),
                ('service', models.FloatField(default=0)),
                ('taste', models.FloatField(default=0)),
                ('foodtype', models.CharField(max_length=50)),
                ('shoplevel', models.CharField(max_length=50)),
                ('envi', models.FloatField(default=0)),
                ('avgcost', models.IntegerField(default=0.0)),
                ('street_address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set([('urlID',)]),
        ),
        migrations.AddField(
            model_name='comment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shop'),
        ),
    ]
