# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('username', models.CharField(blank=True, default='无名', max_length=32, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='无名', max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮件地址')),
                ('gender', models.CharField(default='男', max_length=1, verbose_name='性别')),
                ('latitude', models.FloatField(default=40.0, verbose_name='纬度')),
                ('longitude', models.FloatField(default=116.33, verbose_name='经度')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户页面信息',
                'verbose_name_plural': '用户页面信息',
                'db_table': 'ProfileSite',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='无名', max_length=32, verbose_name='姓名'),
        ),
    ]
