# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='姓名')),
                ('gender', models.CharField(default='男', max_length=1, verbose_name='性别')),
                ('latitude', models.FloatField(default=40.0, verbose_name='纬度')),
                ('longitude', models.FloatField(default=116.33, verbose_name='经度')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户详情',
                'verbose_name_plural': '用户详情',
                'db_table': 'Profile',
            },
        ),
    ]
