# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170705_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to=settings.AUTH_USER_MODEL, verbose_name='friend'),
        ),
    ]
