# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20170704_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_ID', models.CharField(blank=True, default='无名', max_length=32, verbose_name='好友ID')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profilesite',
            name='email',
            field=models.EmailField(blank=True, default='.@.', max_length=254, verbose_name='电子邮件地址'),
        ),
    ]
