# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170704_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': '好友', 'verbose_name_plural': '好友'},
        ),
        migrations.AlterModelTable(
            name='friend',
            table='Friend',
        ),
    ]
