# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user_request_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='request_friend',
        ),
        migrations.AddField(
            model_name='user',
            name='accept_request_friend',
            field=models.ManyToManyField(related_name='_user_accept_request_friend_+', to=settings.AUTH_USER_MODEL, verbose_name='accept_request_friend'),
        ),
        migrations.AddField(
            model_name='user',
            name='send_request_friend',
            field=models.ManyToManyField(related_name='_user_send_request_friend_+', to=settings.AUTH_USER_MODEL, verbose_name='send_request_friend'),
        ),
    ]
