# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170704_1738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='MyFriend',
        ),
    ]
