# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170704_1739'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myfriend',
            table='MyFriend',
        ),
    ]
