# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 05:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170706_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_friend',
            name='from_user',
            field=models.CharField(blank=True, default='无ID', max_length=32, verbose_name='好友ID'),
        ),
        migrations.AlterField(
            model_name='request_friend',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
